FROM rust:1.96.0-alpine3.23 AS builder
RUN apk add --no-cache musl-dev
RUN cargo install sqlx-cli --no-default-features --features rustls,postgres

FROM alpine:3.23
RUN apk add --no-cache ca-certificates
COPY --from=builder /usr/local/cargo/bin/sqlx /usr/local/bin/sqlx
WORKDIR /migrations
COPY migrations .
ENTRYPOINT ["sqlx", "migrate", "run", "--source", "/migrations"]
